### ISSUE TITLE
getNearestNode error

### ISSUE THREAD

**Issue by kmligue** [devloopsnet/typesense-php#3]
```
$client = new Client(array(
    'api_key' => $collection->typesense_api_key,
    'nodes' => array(
        array(
            'host' => $collection->typesense_host,
            'port' => $collection->typesense_port,
            'protocol' => $collection->typesense_protocol
        )
    )
));

$response = $client->collections->create(
    array(
        'name' => $collection->collection_name,
        'fields' => $fields,
        'default_sorting_field' => $default_sorting_field,
    )
);
```

i get a ```Return value of Devloops\Typesence\Lib\Configuration::getNearestNode() must be an instance of Devloops\Typesence\Lib\Node, null returned```

any idea?

**Comment by AbdullahFaqeir** [comment]
@kmligue Please accept my apologies for taking so long to reply to your issue as I've been drowned in work, I'll release a fix and  new version by the end of the day.

Thank you.

**Comment by AbdullahFaqeir** [comment]
@kmligue fixed in https://github.com/devloopsnet/typesense-php/commit/b9d00fb9afe23a4d0debe53b3e6b6a514c687b14
